### ISSUE TITLE
Set the dispatching rule in project.simulate()

### ISSUE THREAD

**Issue by taiga4112** [pDESy/pDESy#37]
It would be nice to be able to set dispatching rule in ``project.simulate()`` like this.

```py
project.simulate(1000, rule=DispatchingRule.FIFO)
```

**Comment by taiga4112** [comment]
- A Project has `task_priority_rule`.
- A Task has `worker_priority_rule` and `facility_priority_rule`.

**Comment by taiga4112** [comment]
## For adding a new task priority rule
If we want to add a new task priority rule, we should do the following processes:

1. Add the rule name in the [TaskPriorityRule class](https://github.com/pDESy/pDESy/blob/315b204dae99a377319c59998c48daebf781046f/pDESy/model/base_priority_rule.py#L13) in model/base_priority_rule.py
2. Add the sort logic in the [BaseProject.__sort_task()](https://github.com/pDESy/pDESy/blob/315b204dae99a377319c59998c48daebf781046f/pDESy/model/base_project.py#L763)

## For adding a new worker or facility priority rule
If we want to add a new resource priority rule, we should do the following processes:

1. Add the rule name in the [ResourcePriorityRule class](https://github.com/pDESy/pDESy/blob/315b204dae99a377319c59998c48daebf781046f/pDESy/model/base_priority_rule.py#L7) in model/base_priority_rule.py
2. Add the sort logic in the [BaseProject.__sort_resource()](https://github.com/pDESy/pDESy/blob/315b204dae99a377319c59998c48daebf781046f/pDESy/model/base_project.py#L771)

**Comment by yuiokubo** [comment]
### Types for priority rule 

**新しく追加したい作業者優先ルール**
- [ ] HSV(High Skill Value)
該当するタスクのスキル値が高い作業者が優先順位が高い
**新しく追加したタスク優先ルール**
- [ ] LRPT(Longest Remaining Process Time)
自身のタスクを含むワークフロー全体の残り工数が多い順に優先度が高い
- [ ] SRPT(Shortest Remaining Process Time)
自身のタスクを含むワークフロー全体の残り工数が少ない順に優先度が高い

**追加した優先ルール**
- [ ] FIFO(First In First Out)
- [ ] VC(Variable Cost)

**Comment by taiga4112** [comment]
> * [ ]  LRPT(Longest Remaining Process Time)
>   自身のタスクを含むワークフロー全体の残り工数が多い順に優先度が高い
> * [ ]  SRPT(Shortest Remaining Process Time)
>   自身のタスクを含むワークフロー全体の残り工数が少ない順に優先度が高い

これは、
* [ ]  LRPT(Longest Remaining Process Time) 
Taskだけ
* [ ]  LWRPT(Longest Workflow Remaining Process Time)
Workflowのcritical pathで
* [ ]  SRPT(Shortest Remaining Process Time)
Taskだけ
* [ ]  SWRPT(Shortest Workflow Remaining Process Time)
Workflowのcritical pathで

と分けたほうが良い気がしますがいかがでしょう？

**Comment by yuiokubo** [comment]
そう思います！
 ありがとうございます！！

**Comment by taiga4112** [comment]
Solve
