### ISSUE TITLE
Need "WorkplaceーWorkplace constrain "

### ISSUE THREAD

**Issue by yuiokubo** [pDESy/pDESy#63]
Due to the constraints of the factory layout, it is necessary to fix the movement from one workplace to another workplace.

(example) Conveyor process

<img width="371" alt="スクリーンショット 2021-07-10 5 50 59" src="https://user-images.githubusercontent.com/40065086/125134783-e621d480-e142-11eb-9597-f16e4d5c7626.png">

**Comment by taiga4112** [comment]
Thank you for creating an important issue.
However, I think your figure does not describe pDESy project model well as followings:
- Each conveyor (Workplace) does not have Tasks
- Component has Tasks

My dirty sketch about this problem is attached.
<img src="https://user-images.githubusercontent.com/12507469/125157193-73494580-e1a4-11eb-8fd0-5c81b861092a.png" width="50%">

**Comment by taiga4112** [comment]
I think there are two possible options for solving this.

Assume that task A and task B have a dependency (A->B), and there are two workplaces that have the facilities to execute task A and task B (wp1 & wp2). Consider the situation where task A is executed by the facility of wp1.

1. 
Add a constraint to the simulation calculation logic that whenever task B is executed, the facility in wp1 must be used.

2.
Modify the current model. Specifically, create four Workspaces (wp1A, wp1B, wp2A, wp2B), and add the constraint to the Workspace model that wp1B can only receive components from wp1A and wp2B can only receive components from wp2A.

**Comment by taiga4112** [comment]
I believe that `op2)` is better than `op1` in the viewpoint of rational modeling,
Here is an updated concept figure for solving this problem.

<img src="https://user-images.githubusercontent.com/12507469/125157815-033cbe80-e1a8-11eb-9af7-9d1ac8aa4a38.png" width="50%">

**Comment by taiga4112** [comment]
I will add this function in near future.
